### ISSUE TITLE
Abgrenzung SE1

### ISSUE THREAD

**Issue by raphiz** [openhsr/git-github-workshop#1]
Im Modul SE1 wird das Thema Konfigurationsmanagement mit Git thematisiert.
Ich möchte Doppelspurigkeiten zwischen dem Git/Github Workshop und der Vorlesung so gut wie möglich vermeiden. Nach der Vorlesung musste ich aber feststellen, der Inhalt der Vorlesung sehr breit gewählt ist - während sich der Workshop auf die Grundlagen / Basics von Git konzentriert (und vor allem die Konzepte dahinter). [Die Inhaltsübersicht](https://github.com/openhsr/git-github-workshop/blob/master/notes/00-overview.md) für den Workshop unterscheidet sich schon wesentlich - primär dadurch,dass erweiterte Funktionen wie Stashing nicht direkt thematisiert werden.

Für mich wäre es wichtig, im Gegensatz zur Vorlesung sich im Workshop auf folgende Inhalte (ergänzend zur aktuellen  Inhaltsübersicht) zu fokussieren:
- Terminologie klären - und Konzepte wie Staging, Branching, Commit, HEAD, Tags usw. mit allen Konsequenzen im Git-Universum _verstehen_
- Voller Fokus auf Git und vergleiche zu SVN/CVS/Mercurial nur dann, wenn von den Teilnehmer gefragt
- Erweiterte Funktionen wie Stashing, Patchset usw. als weiterführende Resourcen vermerkt aber kein Schwerpunkt des Workshops.
- Fokus auf Praxisbezug
- Oberstes Ziel: Durch ein tiefes Verständnis Spass an der Verwendung von Git bekommen und das Interesse auf Mehr wecken

@bytinbit @fabianhauser @Excape @jmatj @murieletrentini @olidias @michiwieland @seboschtion @pacs01 @marshalluous Habt Ihr Ideen/Ergänzungen oder etwas was euch komplett in der Vorlesung gefehlt hat, dass ihr euch in einem Workshop wünschen würdet? 
(ich hoffe ich habe niemand vergessen :wink: - sonst gerne weitersagen)

**Comment by fabianhauser** [comment]
Würde auch in erster Linie die Basics behandeln und den Fokus auf die praktische Anwendung legen.

Evtl. ist Git Flow in diesem Zusammenhang noch interessant?

**Comment by jmatj** [comment]
Meiner Meinung nach ist Doppelspurigkeit berechtigt, wenn man bedenkt, dass SE1 erst im 3. Semester stattfindet. Man kann schon argumentieren, dass man git erst im Engineering Projekt richtig braucht.

Aber ich hoffe schon, dass in Zukunft vermehrt in den Übungen auf git gesetzt wird, vorallem mit den Vorlagen. Grundsätzlich finde ich, dass der Workshop die Grundkonzepte abdecken sollte, mit dem Ziel das man die Basiswerkzeuge kennt, auch gerade im Zusammenhang mit Github.

**Comment by raphiz** [comment]
[Habe die Übersicht angepasst](https://github.com/openhsr/git-github-workshop/blob/master/notes/00-overview.md#abgrenzung-zu-konfigurationsmanagement-mit-git-in-software-engineering-1)
