### ISSUE TITLE
Rundmail an Studierende

### ISSUE THREAD

**Issue by fabianhauser** [openhsr/git-github-workshop#6]
> Hallo zusammen
>
> [Git](https://de.wikipedia.org/wiki/Git) dürfte vielen von euch bereits ein Begriff sein – das Kommandozeilentool zur Verwaltung von Source Code ist heute nicht mehr wegzudenken. Nicht nur in der Open-Source-Community findet Git inzwischen vielseitig Anwendung, sondern auch in der Privatwirtschaft ist Git der de-facto-Standard.
> 
> Leider wird Git an der HSR nur am Rand besprochen – eine Lücke die wir füllen möchten!
>
> Aus diesem Grund organisiert der [Verein open\HSR](https://www.openhsr.ch/) einen Workshop zu Git und GitHub.
>
> Die Teilnahme ist kostenlos - einzige Voraussetzung ist eine [Mitgliedschaft im open\HSR](https://www.openhsr.ch/community/#werde-mitglied) (was ebenfalls kostenlos und unkompliziert ist :slightly_smiling_face:).
>
> [Melde dich jetzt hier auf Doodle mit deiner HSR-E-Mail-Adresse](https://doodle.com/poll/cfb8pss44tcbzzba) zu einer der beiden Durchführungen an! Durchführungen sind am 04.04.2019 und 09.04.2019 jeweils um 17:10 / Raum 1.277 mit einer Beschränkung von 20 Personen. First Come, First Served!
>
> Dein open\HSR
>
> PS: Wir suchen noch nach Helfern, welche sich gut mit Git (insb. den `git`-Kommandozeilen-Befehlen) auskennen, zur Unterstützung des interaktiven Workshop-Teils. Falls du dich auskennst, melde dich doch mit einer Antwort auf dieses E-Mail!

**Comment by fabianhauser** [comment]
@das-g passt das so? Ich würde vorschlagen, wir senden das E-Mail für den Moment mal an `stud.i`, `stud.m` und `stud.e`.

**Comment by das-g** [comment]
Hab' ein paar Edits gemacht.

Sollten die Daten der beiden Durchführungen noch ins Email? Und vielleicht sollten wir kurz sagen, was die Aufgabe(n) von potenziellen Helfern wären?

**Comment by fabianhauser** [comment]
@das-g danke für die Inputs, habe das noch hinzugefügt, denkst du, wir können das so versenden?

**Comment by das-g** [comment]
Passt. Raus damit!

**Comment by fabianhauser** [comment]
Done! :tada:
